server.port=${PORT:8050}

spring.datasource.url=jdbc:postgresql://localhost:5432/ag_invoice?currentSchema=cloudbeds
spring.datasource.username=snap
spring.datasource.password=snap
#spring.datasource.url=jdbc:postgresql://140.82.30.253:5432/agtech_cr_db?currentSchema=cloudbeds
#spring.datasource.username=agtech_cr
#spring.datasource.password=A58T$p8Hr@

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

url.keygenerator=http://localhost:8024/keygenerator/api/v1/create

#AMQP RabbitMQ configuration
#atvadapter.rabbitmq.queue=invoice-queue
#atvadapter.rabbitmq.server=localhost
#atvadapter.rabbitmq.userName=guest
#atvadapter.rabbitmq.password=guest
#atvadapter.rabbitmq.virtualHost=/

atvadapter.rabbitmq.queue=invoice-queue
#atvadapter.rabbitmq.server=10.39.96.3
atvadapter.rabbitmq.server=140.82.31.180
atvadapter.rabbitmq.userName=luvitechlvd
atvadapter.rabbitmq.password=luvitechlvd2019$
atvadapter.rabbitmq.virtualHost=/
atvadapter.rabbitmq.port=5672

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
